# Generated by Django 5.1.4 on 2024-12-12 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('fraud_detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('result', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_detection',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('amt', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city_pop', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('unix_time', models.BigIntegerField()),
                ('merch_latitude', models.FloatField()),
                ('merch_longitude', models.FloatField()),
                ('processed_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
