# Generated by Django 5.1.4 on 2025-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="fraud_probability",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="model_version",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
